name: Fd

on:
  release:
    types: released

jobs:
  linux:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: robinraju/release-downloader@v1.3
        with:
          repository: ${{ github.repository }}
          latest: true
          fileName: "*"

      - name: Process.
        env:
          ADDITIONAL_BUILD: ${{ secrets.ADDITIONAL_BUILD_NUMBER }}
        run: |
          mkdir -p ~/.ssh/
          install -m 600 /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.FD_SSH_PRIVATE }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          
          fileApk=`find . | grep .apk -m 1`
          echo "$fileApk"
          fileAapt2=$(ls $ANDROID_SDK_ROOT/build-tools/**/aapt2 | tail -1)
          echo "$fileAapt2"
          $fileAapt2 dump badging $fileApk > output.txt
          
          versionCode=`grep versionCode output.txt | sed "s/versionCode/#/g" | cut -d'#' -f  2 | cut -d"'" -f 2`
          versionName=`grep versionName output.txt | sed "s/versionName/#/g" | cut -d'#' -f  2 | cut -d"'" -f 2`


          echo "Host *" > ~/.ssh/config
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          echo "UserKnownHostsFile=/dev/null" >> ~/.ssh/config


          git config --global user.email "${{ secrets.FD_GIT_EMAIL }}"
          git config --global user.name "${{ secrets.FD_GIT_NAME }}"
          
          git clone git@gitlab.com:fdroid/fdroiddata.git r
          cd r
          git remote add fork ${{ secrets.FD_SSH_URL }}
          git branch update
          git checkout update

          
          file=`find . | grep forkgam`

          cp `find . | grep fd_part.txt -m 1` part.txt
          cp `find . | grep fd_end.txt -m 1` end.txt

          countLines=`wc -l end.txt | cut -d' ' -f 1`
          for dummy in `seq 1 $countLines`
          do
            sed -i '$ d' $file
          done

          echo "" >> $file
          echo "`cat part.txt`" >> $file
          echo "" >> $file
          echo "`cat end.txt`" >> $file

          ADDITIONAL_BUILD_NUMBER=$((ADDITIONAL_BUILD / 10000))

          sed -i "s/V_NAME/${versionName}/g" $file
          sed -i "s/V_CODE/${versionCode}/g" $file
          sed -i "s/V_NUM/${ADDITIONAL_BUILD_NUMBER}/g" $file
          
          git add $file
          git commit -m "Updated Forkgram to ${versionName}."
          
          git push --force --set-upstream fork update
